import Head from 'next/head'
import {ButtonBase} from '@reusejs/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full flex flex-col justify-center align-middle ml-20 mr-20 h-screen'>
        <h1 className='text-3xl font-medium text-gray-600  ml-16 mr-16 w-4/5'>Welcome to Favourite NPM Packages</h1>
        <div className='flex justify-center align-middle mt-12 ml-16 mr-16 border-gray-500 border-2 rounded-md h-80 w-4/5'>
          <div className='flex flex-col justify-center align-middle w-fit h-80'>
            <h1 className='text-2xl font-medium text-gray-600 mb-10'>Welcome to Favourite NPM Packages</h1>
            <div className='w-full flex justify-center'>
              <ButtonBase label="Add to fav" buttonBaseClasses={{backgroundColor:"bg-blue-600"}} onClick={()=>console.log("hello")}/>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
