import Head from "next/head";
import { useEffect, useState } from "react";
import { ButtonBase, NavigationBase } from "@reusejs/react";
import HasFav from "../components/HasFav";
import DeleteModel from "../components/DeleteModel";
import { getData } from "../store/npmSlice";
import { useDispatch, useSelector } from "react-redux";

import Link from "next/link";

export default function Home() {
  const fav = useSelector((state) => state.favNPM.favPackages);

  const dispatch = useDispatch();
  const searchdata = useSelector((state) => state.favNPM.search);

  useEffect(() => {
    dispatch(getData(searchdata));
  }, [dispatch, searchdata]);

  const [deleted, SetDelete] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBase
        left={function noRefCheck() {
          return "Betalectic"
        }}
        leftArrangement="bg-red-50"
        middle={function noRefCheck() {
          return ["amir","sohail"]
        }}
        middleArrangement="bg-green-50 ml-8 flex-1 justify-end"
        rightArrangement="bg-blue-50"
      />

      {fav.length > 0 ? (
        <div>
          {deleted ? <DeleteModel SetDelete={SetDelete} /> : ""}
          <HasFav fav={fav} SetDelete={SetDelete} />
        </div>
      ) : (
        <main className="w-full flex flex-col justify-center align-middle ml-20 mr-20 h-screen">
          <h1 className="text-3xl font-medium text-gray-600  ml-16 mr-16 w-4/5">
            Welcome to Favourite NPM Packages
          </h1>
          <div className="flex justify-center align-middle mt-12 ml-16 mr-16 border-gray-500 border-2 rounded-md h-80 w-4/5">
            <div className="flex flex-col justify-center align-middle w-fit h-80">
              <h1 className="text-2xl font-medium text-gray-600 mb-10">
                Welcome to Favourite NPM Packages
              </h1>
              <div className="w-full flex justify-center">
                <Link href="/searchfav">
                  <ButtonBase label="Add to fav" variant="green" />
                </Link>
              </div>
            </div>
          </div>
        </main>
      )}
    </>
  );
}
